language: ruby
rvm:
  - rvm 2.1.1
  - rvm 2.1.5
  - rvm 2.2.0
  - rvm 2.2.1
  - rvm 2.2.2

before_install:
  - sudo apt-get install postgresql-9.3 postgresql-server-dev-9.3 libpq-dev
install:
  - bundle
